export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  const isTest = process.env.NODE_ENV === "test";

  if (isTest) {
    // In tests, just render children without <html> / <body>
    return <>{children}</>;
  }

  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
